pipeline:
  build:
    image: node:6.9.2
    commands:
      - npm install
      - apt-get update
      - apt-get install -y expect
      #- ./monitor.expect
      - tail -f /dev/null
  slack:
    image: plugins/slack
    channel: drone
    username: drone
    when:
      status: [ success, failure ]

services:
  geth:
    image: cp2017/geth:2017-01-26.02
    pull: true
    container_name: geth
    environment:
     - GETH_TEST_DATABASE=true
     - GETH_BOOTSTRAP=false
